apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: ecg
  labels:
    app: prefect-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
        - name: prefect-agent
          image: cobrachainsaw/prefect-etl:latest
          command: ["prefect", "agent", "start", "-q", "ecg_queue"]
          env:
            - name: PREFECT_API_URL
              value: http://prefect-api.ecg.svc.cluster.local:4200/api
          volumeMounts:
            - name: spark-jobs
              mountPath: /app/spark_jobs
            - name: spark-dir
              mountPath: /app/scripts
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: spark-jobs
          hostPath:
            path: /mnt/etl/spark/jobs
            type: Directory
        - name: spark-dir
          hostPath:
            path: /mnt/etl/spark
            type: Directory
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
