apiVersion: v1
kind: Service
metadata:
  name: prefect-api
  namespace: ecg
spec:
  ports:
    - port: 4200
      targetPort: 4200
  selector:
    app: prefect-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-api
  namespace: ecg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-api
  template:
    metadata:
      labels:
        app: prefect-api
    spec:
      containers:
        - name: prefect-api
          image: cobrachainsaw/prefect-etl:latest  # Your custom or base image
          command: ["prefect", "server", "start", "--host", "0.0.0.0"]
          ports:
            - containerPort: 4200
          env:
            - name: PREFECT_API_DATABASE_CONNECTION_URL
              value: postgresql+asyncpg://prefect:prefect@postgres.ecg.svc.cluster.local:5432/prefect
