apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  namespace: ecg
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: spark
          image: cobrachainsaw/spark-etl:latest
          command:
            ["/bin/bash", "-c", "/app/spark-submit.sh"]
          env:
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: AWS_REGION
              value: us-east-1
          volumeMounts:
            - name: spark-jobs
              mountPath: /app/spark_jobs
      volumes:
        - name: spark-jobs
          hostPath:
            path: /mnt/etl/spark/jobs
            type: Directory
