version: '3.8'

services:
  # — MinIO for object storage —
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - ecg_net

  # — Zookeeper for Kafka —
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - ecg_net

  # — Kafka for message queuing —
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - ecg_net

  # — Spark with Iceberg support —
  spark:
    build: ./spark  # Contains Dockerfile using tabulario/spark-iceberg:latest
    container_name: spark
    depends_on:
      - minio
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
    volumes:
      - ./spark/jobs:/app/spark_jobs
      - ./spark/spark-submit.sh:/app/spark-submit.sh
    networks:
      - ecg_net

  # — Prefect Agent (executes flows) —
  prefect:
    image: prefecthq/prefect:2-python3.9
    container_name: prefect
    depends_on:
      - api
      - spark
    command: prefect agent start -q default
    volumes:
      - ./prefect:/app/prefect
      - ./spark/jobs:/app/spark_jobs
      - ./spark/spark-submit.sh:/app/spark-submit.sh
    environment:
      PREFECT_API_URL: http://api:4200
    networks:
      - ecg_net

  # — Prefect API Server —
  api:
    image: prefecthq/prefect:2
    container_name: prefect-api
    command: prefect orion start --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - ecg_net

volumes:
  minio-data:
  warehouse:

networks:
  ecg_net:
