version: '3'

services:
  # — PostgreSQL for Prefect API —
  postgres:
    image: postgres:15
    container_name: prefect-postgres
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecg_net

  # — MinIO for object storage —
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - ecg_net

  # — Kafka using KRaft mode —
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: kraft-cluster-1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://host.docker.internal:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - ecg_net

  # — Spark with Iceberg support —
  spark:
    build:
      context: "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/spark"
    container_name: spark
    entrypoint: ["/bin/bash"]
    command: ["-c", "tail -f /dev/null"]
    depends_on:
      - minio
      - kafka
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
    volumes:
      - "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/spark/jobs:/app/spark_jobs"
      - "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/spark/spark_submit.sh:/app/spark-submit.sh"
    networks:
      - ecg_net

  # — Prefect API Server —
  api:
    build:
      context: "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/prefect"
      dockerfile: Dockerfile.prefect
    container_name: prefect-api
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@prefect-postgres:5432/prefect
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecg_net

  # — Prefect Agent —
  prefect:
    build:
      context: "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/prefect"
      dockerfile: Dockerfile.prefect
    container_name: prefect
    depends_on:
      - api
    command: prefect agent start -q ecg_queue
    environment:
      PREFECT_API_URL: http://prefect-api:4200/api
    volumes:
      - "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/prefect:/app/prefect"
      - "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/spark/jobs:/app/spark_jobs"
      - "C:/Users/vinay/OneDrive/Documents/GitHub/ETL_V1/spark/spark_submit.sh:/app/spark-submit.sh"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ecg_net


volumes:
  minio-data:
  kafka-data:
  postgres-data:

networks:
  ecg_net:
